# Generated by Django 4.2.16 on 2024-11-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_hotelphotos_hotel_alter_roomphotos_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_description_ky',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name_ky',
        ),
        migrations.AlterField(
            model_name='rating',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='store.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='store.hotel'),
        ),
    ]
